Repository FWDekker/mommy, pull requests merged in 2023-11, with the labels that each got.

#69 💨 mommy now uses the much faster vm actions~
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: tooling

#68 🍳 mommy uses actions/checkout@v4 now~
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: tooling

#70 📂 mommy allows custom dirs during make~
  CHANGELOG.md
  GNUmakefile
Labels: tooling, code quality

#71 👭 mommy publishes to a debian repo~
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  GNUmakefile
  README.md
  pkg/rpkg/mommy.spec.rpkg
  pkg/rpkg/rpkg.conf
  pkg/rpkg/rpkg.macros
  pkg/rpm/rpkg.conf
Labels: code quality, packaging

#72 🤍 v1.2.5~
  .editorconfig
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  GNUmakefile
  README.md
  pkg/rpkg/mommy.spec.rpkg
  pkg/rpkg/rpkg.conf
  pkg/rpkg/rpkg.macros
  pkg/rpm/rpkg.conf
  version
Labels: release

#73 🚒 mommy fixes her apt repository release script~
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  version
Labels: bug, tooling, packaging

#74 🤎 v1.2.6~
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  version
Labels: release

#82 ✂️ a few simple fixes~
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  src/main/man/man1/mommy.1
  src/main/sh/mommy
  src/test/sh/unit_spec.sh
Labels: bug, documentation: code, tooling, tests, documentation: user

#83 🕰️ mommy fixes changelog usage in debs and rpms~
  .fpm
  CHANGELOG.md
  GNUmakefile
  README.md
  pkg/fpm/deb.changelog
  pkg/fpm/rpm.changelog
  pkg/rpkg/mommy.spec.rpkg
Labels: enhancement, packaging
