Repository FWDekker/mommy, pull requests merged in 2023-08, with the labels that each got.

#62 💿 mommy hopefully fixed netbsd vm issues~
  .github/workflows/ci.yml
Labels: bug

#63 🎨 mommy simplified her makefile~
  GNUmakefile
  README.md
  src/test/sh/integration_spec.sh
Labels: tooling, code quality

#61 🫣 mommy finds your config with an environment variable now~ +nixos
  .gitattributes
  .github/workflows/ci.yml
  README.md
  src/main/sh/mommy
Labels: enhancement, packaging

#64 💜 v1.2.4~
  .gitattributes
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  GNUmakefile
  README.md
  src/main/sh/mommy
  src/test/sh/integration_spec.sh
  version
Labels: release
